### ISSUE TITLE
NPC system - fix bugs

### ISSUE THREAD

**Issue by kwongaeu** [The-Grinnell-College-Experience-Team/GCE-Backend#53]
Fix some bugs in the NPC system.
- The NPC object runs away when the main character gets closer to it.
- I think it is a side effect of the `move_and_slide()` function in the NPC scripts.
- But after commenting on this function, the main character cannot conflict with the NPC objects anymore.

**Comment by moizyousufi** [comment]
reworked NPCs entirely.
